config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :payments
  resources :categories
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  unauthenticated do
    root "splash#index"
  end

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true, length: { maximum: 250 }
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { only_decimal: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :payments, through: :categories

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  def index
    @categories = current_user.categories.order(created_at: :desc)
  end

  # GET /categories/1
  def show
    @payments = @category.payments.order(created_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  def show; end

  # GET /payments/new
  def new
    @category = current_user.categories
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
    @category = current_user.categories
  end

  # POST /payments
  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      redirect_to category_path(id: @payment.category_id), notice: 'Payment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /payments/1
  def update
    if @payment.update(payment_params)
      redirect_to @payment, notice: 'Payment was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /payments/1
  def destroy
    @payment.destroy
    redirect_to payments_url, notice: 'Payment was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:category_id, :name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="flex justify-between items-center m-3 p-3 bg-white text-terciary">
  <%=image_tag category.icon, class: "w-16 h-16" %>
  <h5 class="grow text-left px-3"><%= category.name %></h5>
  <h5>$<%= category.payments.map {|payment| payment.amount}.sum %></h5>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container mx-auto bg-white px-3 py-2">
    <div class="relative z-0 w-full my-2 group">
      <%= form.text_field :name, autocomplete: "name", autofocus: true, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: true %>
      <label for="floating_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Name</label>
    </div>

    <div class="relative z-0 w-full my-2 group">
      <%= form.url_field :icon, autocomplete: "icon", autofocus: true, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: true %>
      <label for="floating_icon" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Icon</label>
    </div>

    <div class="text-gray-200 font-light text-center my-2 w-full">
      <%= form.submit "Submit", class: "bg-primary hover:bg-blue-700 block py-3 px-4 rounded" %>
    </div>

  </div>



<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="flex flex-col justify-between min-h-screen">
  <section class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
    <i class="fa-solid fa-bars fa-xl md:hidden" id="hamburger-btn"></i>
    <%= button_to "Exit", destroy_user_session_path, method: :delete, class:"uppercase hidden md:block"%>
    <h5 class="font-light grow text-center">CATEGORIES</h5>
  </section>
  <p ss="text-green-500 px-3"><%= notice %></p>

  <div id="categories" class="grow">
    <% @categories.each do |category| %>
      <%= link_to category  do %>
        <%= render category %>
      <% end %>
    <% end %>
  </div>
  <div class="bg-secondary p-4 text-center text-3xl text-white font-light">
    <%= link_to "New Category", new_category_path, class: "border border-white hover:opacity-70 block p-4 rounded" %>
  </div>


</div>

app/views/categories/new.html.erb
<div class="flex flex-col">

  <div class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
    <%= link_to categories_path do %>
      <i class="fa-solid fa-arrow-left fa-xl "></i>
    <% end %>
    <h5 class="font-light grow text-center">ADD CATEGORY</h5>
  </div>

  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div class="flex flex-col justify-between min-h-screen">
  <div class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
    <%= link_to categories_path do %>
      <i class="fa-solid fa-arrow-left fa-xl "></i>
    <% end %>
    <h5 class="font-light grow text-center">PAYMENTS</h5>
  </div>

  <p class="text-green-500 p-3"><%= notice %></p>

  <div class="grow">
    <% @payments.each do |payment| %>
      <div class="flex justify-between items-center m-3 p-3 bg-white text-terciary">
        <div>
          <h5><%= payment.name %></h5>
          <h5><%= payment.created_at.strftime("%Y-%m-%d") %></h5>
        </div>
        <h5>$<%= payment.amount %></h5>
      </div>
    <% end %>
    <h5 class="m-3 p-3 bg-white text-terciary text-center text-2xl">Total for <%= @category.name %>  $<%= @category.payments.map {|payment| payment.amount}.sum %></h5>
  </div>

  <div class="bg-secondary p-4 text-center text-3xl text-white font-light">
    <%= link_to "New Transaction", new_payment_path, class: "border border-white hover:bg-blue-700 block p-4 rounded" %>
  </div>

<div>

app/views/layouts/_navbar.html.erb
<div class="fixed w-full left-0 top-0 bg-transparent z-10 h-screen hidden transition-all" id="backdrop"></div>
<nav id="mobile-menu" class="fixed w-3/4 left-0 top-0 bg-blue-400 opacity-90 text-white z-20 h-screen p-4 flex justify-center items-center gap-10 -translate-x-full transition-all">
  <% if user_signed_in? %>
    <h3 class="absolute top-10 text-sm">Signed in as <%= current_user.name %></h3>
  <% end %>
  <ul>
    <% if user_signed_in? %>
    <li><%= button_to "sign out", destroy_user_session_path, method: :delete, class: "text-2xl uppercase"%></li>
    <% else %>
    <li><%= link_to "sign in", new_user_session_path, class: "text-2xl uppercase"%></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class=" bg-gray-100 container mx-auto max-w-sm">
      <%= render partial: "layouts/navbar" %>
      <%= yield %>
    </main>

  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container mx-auto bg-white px-3 py-2">
    <div>
      <%= form.label :category_id, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400" %>
      <%= form.select :category_id, @category.map { |category| [category.name, category.id] }, {}, { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"} %>
    </div>

    <div class="relative z-0 w-full my-2 group">
      <%= form.text_field :name, autocomplete: "name", autofocus: true, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: true, id: "name" %>
      <label for="floating_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Name</label>
    </div>

    <div class="relative z-0 w-full my-2 group">
      <%= form.number_field :amount, autocomplete: "amount", class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: true, id: "amount" %>
      <label for="floating_amount" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Amount</label>
    </div>

    <div class="text-gray-200 font-light text-center my-2 w-full">
      <%= form.submit "Submit", class: "bg-primary hover:bg-blue-700 block py-3 px-4 rounded" %>
    </div>
  </div>


<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Category:</strong>
    <%= payment.category_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<div class="flex flex-col">

  <div class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
    <%= link_to categories_path do %>
      <i class="fa-solid fa-arrow-left fa-xl "></i>
    <% end %>
    <h5 class="font-light grow text-center">ADD TRANSACTION</h5>
  </div>

  <%= render "form", payment: @payment %>


</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>
<%= @payment.category.id %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>

app/views/splash/index.html.erb
<section class="container mx-auto flex justify-center">
  <div class="w-screen min-h-screen mx-3 py-3 text-center flex flex-col">
    <div class="grow text-center flex justify-center items-center">
      <div class="italic font-black text-3xl text-terciary">PayTracker</div>
    </div>
    <div>
      <div class="text-gray-300 font-light my-2"><%= link_to "Log in", new_user_session_path, class: "bg-primary hover:bg-blue-700 text-white block py-3 px-4 rounded-sm" %></div>
      <div class="text-gray-300 font-light my-2"><%= link_to "Sign up", new_user_registration_path, class: "bg-primary hover:bg-blue-700 text-white block py-3 px-4 rounded-sm" %></div>
    </div>
  </div>
</section>